"""阶段 3 的本地安全与费用保护常量。"""

ASK_WINDOW_SECONDS = 60.0
ASK_MAX_CALLS_PER_WINDOW = 5
ASK_MAX_UNITS_PER_PROCESS = 50

AGENT_WINDOW_SECONDS = 60.0
AGENT_MAX_CALLS_PER_WINDOW = 3
AGENT_MAX_UNITS_PER_PROCESS = 20

WORKFLOW_WINDOW_SECONDS = 60.0
WORKFLOW_MAX_CALLS_PER_WINDOW = 10

INDEX_WINDOW_SECONDS = 60.0 * 60
INDEX_MAX_CALLS_PER_WINDOW = 5
INDEX_MAX_BATCHES_PER_OPERATION = 20
INDEX_MAX_BATCHES_PER_PROCESS = 100

STAGE_WINDOW_SECONDS = 60.0
STAGE_MAX_CALLS_PER_WINDOW = 10
DELETE_WINDOW_SECONDS = 60.0
DELETE_MAX_CALLS_PER_WINDOW = 10
WEB_PREVIEW_WINDOW_SECONDS = 60.0
WEB_PREVIEW_MAX_CALLS_PER_WINDOW = 3

PENDING_UPLOAD_TTL_SECONDS = 24 * 60 * 60
MAX_UPLOAD_PDF_PAGES = 200
MAX_UPLOAD_EXTRACTED_CHARACTERS = 200_000
MAX_UPLOAD_FILES_PER_BATCH = 20

EMBEDDING_TIMEOUT_SECONDS = 30
EXTERNAL_API_MAX_RETRIES = 2
